//atomsで使っている個別的なパラメータをまとめて定義
export const BUTTON_PRIMARY = "btn-primary"
export const BUTTON_SECONDARY = "btn-secondary"
export const BUTTON_WARNING = "btn-warning"
export const BUTTON_DANGER = "btn-danger"
export const BUTTON_SUCCESS = "btn-success"
export const BUTTON_DARK = "btn-dark"
export const BUTTON_LIGHT = "btn-light"

export const BADGE_PRIMARY = "badge-primary"
export const BADGE_SECONDARY = "badge-secondary"
export const BADGE_WARNING = "badge-warning"
export const BADGE_DANGER = "badge-danger"
export const BADGE_SUCCESS = "badge-success"
export const BADGE_DARK = "badge-dark"
