export const MINI_SIZE = "mini"
export const SMALL_SIZE = "small"
export const NORMAL_SIZE = "normal"
export const LARGE_SIZE = "large"
export const XLARGE_SIZE = "xlarge"
export const SQUARE_SHAPE = "square"
export const CIRCLE_SHAPE = "circle"
