import { CardListType } from "@/components/organisms/viewSite/core/types/cardListType"
import { RasterSourceSpecification, GeoJSONSourceSpecification } from "maplibre-gl"
export const cardLayerList: CardListType[] = [
  {
    logoImg: "",
    text: "今昔マップ",
    dangerBadge: "歴史",
    warningBadge: "マップ",
    primaryBadge: "ベースマップ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: true,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "jrEastRealTimeLocateDataCallback",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "changeLayerOrder",
    layer: {
      id: "konjakumap",
      type: "raster",
      sourceId: "konjakumap",
      source: {
        type: "raster",
        tiles: ["https://ktgis.net/kjmapw/kjtilemap/tokyo50/03/{z}/{x}/{y}.png"],
        tileSize: 512,
        scheme: "tms",
        maxzoom: 16,
        minzoom: 8,
        attribution: "今昔マップ",
      } as RasterSourceSpecification,
      layout: {
        visibility: "visible",
      },
      paint: {
        "raster-opacity": 1,
      },
    },
  },
  {
    logoImg: "",
    text: "オープンストリートマップ",
    dangerBadge: "通常地図",
    warningBadge: "マップ",
    primaryBadge: "ベースマップ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: true,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "buttonClicked",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "changeLayerOrder",
    layer: {
      id: "osm-map",
      type: "raster",
      sourceId: "osm-map",
      source: {
        type: "raster",
        tiles: ["https://tile.openstreetmap.jp/styles/osm-bright-ja/{z}/{x}/{y}.png"],
        tileSize: 512,
        attribution: "OpenStreetMap",
      } as RasterSourceSpecification,
      layout: {
        visibility: "visible",
      },
      paint: {
        "raster-opacity": 1,
      },
    },
  },
  {
    logoImg: "/assets/logos/tokyoLogo.webp",
    text: "都営バスルート",
    dangerBadge: "交通",
    warningBadge: "バス",
    primaryBadge: "ラインデータ",
    darkBadge: "オープンデータチャレンジ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: false,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "tokyoMetroRealTimeDataCallback",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "buttonClicked",
    layer: {
      id: "line",
      type: "line",
      sourceId: "LineToeiBus",
      source: {
        type: "geojson",
        data: "/geojson/LineToeiBus.geojson",
      } as GeoJSONSourceSpecification,
      layout: {
        "line-join": "round",
        "line-cap": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#00FF00",
        "line-width": 3,
        "line-opacity": 1,
      },
    },
  },
  {
    logoImg: "/assets/logos/default.webp",
    text: "町丁目人口あたりのハローサイクルポート数",
    dangerBadge: "交通",
    warningBadge: "シェアサイクル",
    primaryBadge: "ポリゴンデータ",
    darkBadge: "オープンデータチャレンジ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: false,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "openAllDialogs",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "changeLayerOrder",
    layer: {
      id: "polygon",
      type: "fill",
      sourceId: "BaseCityBlocks",
      source: {
        type: "geojson",
        data: "/geojson/Block_Tokyo_FeaturesToJSON.geojson",
      } as GeoJSONSourceSpecification,
      layout: {
        visibility: "visible",
      },
      paint: {
        "fill-color": [
          "interpolate",
          ["linear"],
          ["get", "Capacity_面積"],
          0,
          "#f2f0f7",
          10,
          "#cbc9e2",
          20,
          "#9e9ac8",
          50,
          "#6a51a3",
        ],
        "fill-opacity": 1,
      },
    },
  },
]
