import { CardListType } from "@/domain/types/cardListType"

export const cardList: CardListType[] = [
  {
    logoImg: "/assets/logos/jreast.webp",
    text: "JR東日本リアルタイム車両位置データ",
    dangerBadge: "交通データ",
    warningBadge: "鉄道",
    successBadge: "リアルタイム",
    primaryBadge: "ポイントデータ",
    darkBadge: "2024オープンデータチャレンジ限定",
    isShadow: false,
    shape: "square",
    isDisplayLayer: true,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "jrEastRealTimeLocateDataCallback",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "buttonClicked",
  },
  {
    logoImg: "/assets/logos/tokyometro.webp",
    text: "東京メトロリアルタイム運行状況データ",
    dangerBadge: "交通データ",
    warningBadge: "鉄道",
    successBadge: "リアルタイム",
    primaryBadge: "ラインデータ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: false,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "tokyoMetroRealTimeDataCallback",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "buttonClicked",
  },
  {
    logoImg: "/assets/logos/soumusyou.webp",
    text: "2020年度国勢調査メッシュ",
    dangerBadge: "人口データ",
    warningBadge: "国勢調査",
    primaryBadge: "メッシュデータ",
    isShadow: false,
    shape: "square",
    isDisplayLayer: false,
    colorPickerClick: "buttonClicked",
    sliderClick: "buttonClicked",
    infoButtonClick: "openAllDialogs",
    displayButtonClick: "buttonClicked",
    orderButtonClick: "buttonClicked",
  },
]