export const TRAIN_STATION_LAYER = "train-station-layer"
export const TRAIN_LINE_LAYER = "train-line-layer"
export const HELLO_CYCLE_LAYER = "hello-cycle-layer"
export const DOCOMO_BIKE_SHARE_LAYER = "docomo-bike-share-layer"
export const TOEI_BUS_POINT_LAYER = "toei-bus-point-layer"
export const TOEI_BUS_LINE_LAYER = "toei-bus-line-layer"
export const POPULATION_MESH_LAYER = "population-mesh-layer"
